micronaut:
  application:
    name: storeMicronaut
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: ''
    dialect: POSTGRES
    maximum-pool-size: 1
jpa.default.properties.hibernate.hbm2ddl.auto: none
